<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CharacterSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table("characters")->insert([
            [
                'id'=>1,
                'name'=>"Harry James Potter",
                'gender'=>"Male",
                'job'=>"Student",
                'wand'=>'1,11"  Holly  phoenix feather',
                'patronus'=>"Stag",
                'species'=>"Human",
                'birth'=>"1980-07-31",
                'death'=>NULL,
                'house_id'=>1,
            ],
            [
                'id'=>2,
                'name'=>"Ronald Bilius Weasley",
                'gender'=>"Male",
                'job'=>"Student",
                'wand'=>'12"" Ash unicorn tail hair',
                'patronus'=>"Jack Russell terrier",
                'species'=>"Human",
                'birth'=>"1980-03-01",
                'death'=>NULL,
                'house_id'=>1,
            ],
            [
                'id'=>3,
                'name'=>"Hermione Jean Granger",
                'gender'=>"Female",
                'job'=>"Student",
                'wand'=>'10l"" vine wood dragon heartstring',
                'patronus'=>"Otter",
                'species'=>"Human",
                'birth'=>"1979-09-19",
                'death'=>NULL,
                'house_id'=>1,
            ],
            [
                'id'=>4,
                'name'=>"Albus Percival Wulfric Brian Dumbledore",
                'gender'=>"Male",
                'job'=>"Headmaster",
                'wand'=>'15"" Elder Thestral tail hair core',
                'patronus'=>"Phoenix",
                'species'=>"Human",
                'birth'=>"1881-08-30",
                'death'=>"1997-07-30",
                'house_id'=>1,
            ],
            [
                'id'=>5,
                'name'=>"Rubeus Hagrid",
                'gender'=>"Male",
                'job'=>"Keeper of Keys and Grounds | Professor of Care of Magical Creatures",
                'wand'=>'16"" Oak unknown core',
                'patronus'=>NULL,
                'species'=>"Half-Human/Half-Giant",
                'birth'=>"1928-12-06",
                'death'=>NULL,
                'house_id'=>1,
            ],
            [
                'id'=>6,
                'name'=>"Neville Longbottom",
                'gender'=>"Male",
                'job'=>"Student",
                'wand'=>'13"" Cherry unicorn hair',
                'patronus'=>"Non-corporeal",
                'species'=>"Human",
                'birth'=>"1980-07-30",
                'death'=>NULL,
                'house_id'=>1,
            ],
            [
                'id'=>7,
                'name'=>"Fred Weasley",
                'gender'=>"Male",
                'job'=>"Student",
                'wand'=>"Unknown",
                'patronus'=>"Unknown",
                'species'=>"Human",
                'birth'=>"1978-04-01",
                'death'=>"1998-05-02",
                'house_id'=>1,
            ],
            [
                'id'=>8,
                'name'=>"George Weasley",
                'gender'=>"Male",
                'job'=>"Student",
                'wand'=>"Unknown",
                'patronus'=>"Unknown",
                'species'=>"Human",
                'birth'=>"1978-04-01",
                'death'=>NULL,
                'house_id'=>1,
            ],
            [
                'id'=>9,
                'name'=>"Ginevra (Ginny) Molly Weasley",
                'gender'=>"Female",
                'job'=>"Student",
                'wand'=>"Unknown",
                'patronus'=>"Horse",
                'species'=>"Human",
                'birth'=>"1981-08-11",
                'death'=>NULL,
                'house_id'=>1,
            ],
            [
                'id'=>10,
                'name'=>"Garrick Ollivander",
                'gender'=>"Male",
                'job'=>"Wandmaker",
                'wand'=>'12ľ"" Hornbeam dragon heartstring',
                'patronus'=>"Non-corporeal",
                'species'=>"Human",
                'birth'=>"1908-09-25",
                'death'=>NULL,
                'house_id'=>2,
            ],
            [
                'id'=>11,
                'name'=>"Myrtle Elizabeth Warren (Moaning Myrtle)",
                'gender'=>"Female",
                'job'=>"Student",
                'wand'=>"Unknown",
                'patronus'=>"Unknown",
                'species'=>"Ghost",
                'birth'=>"1928-06-14",
                'death'=>"1943-06-13",
                'house_id'=>2,
            ],
            [
                'id'=>12,
                'name'=>"Padma Patil",
                'gender'=>"Female",
                'job'=>"Student",
                'wand'=>"Unknown",
                'patronus'=>"Non-corporeal",
                'species'=>"Human",
                'birth'=>"1979-09-01",
                'death'=>NULL,
                'house_id'=>2,
            ],
            [
                'id'=>13,
                'name'=>"Michael Corner",
                'gender'=>"Male",
                'job'=>"Student",
                'wand'=>"Unknown",
                'patronus'=>"Squirrel",
                'species'=>"Human",
                'birth'=>"1979-09-01",
                'death'=>NULL,
                'house_id'=>2,
            ],
            [
                'id'=>14,
                'name'=>"Marietta Edgecombe",
                'gender'=>"Female",
                'job'=>"Student",
                'wand'=>"Unknown",
                'patronus'=>"Unknown",
                'species'=>"Human",
                'birth'=>NULL,
                'death'=>NULL,
                'house_id'=>2,
            ],
            [
                'id'=>15,
                'name'=>"Severus Snape",
                'gender'=>"Male",
                'job'=>"Professor of Potions | Head of Slytherin",
                'wand'=>"Unknown",
                'patronus'=>"Doe",
                'species'=>"Human",
                'birth'=>"1960-01-09",
                'death'=>"1998-05-02",
                'house_id'=>3,
            ],
            [
                'id'=>16,
                'name'=>"Draco Malfoy",
                'gender'=>"Male",
                'job'=>"Student",
                'wand'=>'10"" Hawthorn unicorn hair',
                'patronus'=>"Unknown",
                'species'=>"Human",
                'birth'=>"1980-06-05",
                'death'=>NULL,
                'house_id'=>3,
            ],
            [
                'id'=>17,
                'name'=>"Nymphadora Tonks",
                'gender'=>"Female",
                'job'=>"Auror",
                'wand'=>"Unknown",
                'patronus'=>"Jack rabbit, Wolf",
                'species'=>"Human",
                'birth'=>"1972-09-01",
                'death'=>"1998-05-02",
                'house_id'=>4,
            ],
            [
                'id'=>18,
                'name'=>"Newton Scamander",
                'gender'=>"Male",
                'job'=>"Employee in the Beast Division of the Department for the Regulation and Control of Magical Creatures",
                'wand'=>"Unknown",
                'patronus'=>"Unknown",
                'species'=>"Human",
                'birth'=>"1897-02-24",
                'death'=>NULL,
                'house_id'=>4,
            ],
            [
                'id'=>19,
                'name'=>"Madame Olympe Maxime",
                'gender'=>"Female",
                'job'=>"Headmistress of Beauxbatons Academy of Magic",
                'wand'=>"Unknown",
                'patronus'=>"Unknown",
                'species'=>"Half-Human/Half-Giant",
                'birth'=>NULL,
                'death'=>NULL,
                'house_id'=>5,
            ],
        ]);
    }
}
